apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJhbW9sa29rYXJlLmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJhbVp5YjJkamNtVmtPa0ZyYjJ0aFFDTXlNREkwSVE9PSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
